export type EventName =
  | 'addToCart'
  | 'cart'
  | 'cartChanged'
  | 'cartId'
  | 'cartLoaded'
  | 'categoryView'
  | 'checkout'
  | 'checkoutOption'
  | 'departmentView'
  | 'finishPayment'
  | 'homeView'
  | 'installWebApp'
  | 'internalSiteSearchView'
  | 'openDrawer'
  | 'orderPlaced'
  | 'otherView'
  | 'pageComponentInteraction'
  | 'pageInfo'
  | 'pageView'
  | 'productClick'
  | 'productComparison'
  | 'productImpression'
  | 'productView'
  | 'promotionClick'
  | 'promoView'
  | 'removeFromCart'
  | 'sendPayments'
  | 'newsletterSubscription'
  | 'viewCart'
  | 'beginCheckout'
  | 'addPaymentInfo'
  | 'addShippingInfo'
  | 'addToWishlist'
  | 'share'
  | 'login'
  | 'search'
  | 'signUp'
  | 'refund'

export interface PixelData {
  id?: string
  event?: EventName
  [data: string]: unknown
}
